[dependencies]

[package]
  cjc-version = "1.0.0"
  compile-option = "-Woff unused"
  description = "仓颉(Cangjie)的Mustache模板引擎"
  link-option = ""
  name = "mustache"
  output-type = "static"
  override-compile-option = ""
  src-dir = ""
  target-dir = ""
  version = "1.1.0"
  package-configuration = {}

[target]
    [target.x86_64-unknown-linux-gnu]
        [target.x86_64-unknown-linux-gnu.bin-dependencies]
            path-option = ["${CANGJIE_STDX_PATH}"]
    [target.x86_64-apple-darwin]
        [target.x86_64-apple-darwin.bin-dependencies]
            path-option = ["${CANGJIE_STDX_PATH}"]
    [target.x86_64-w64-mingw32]
        [target.x86_64-w64-mingw32.bin-dependencies]
            path-option = ["${CANGJIE_STDX_PATH}"]